export default {
    ADD_USER: 'ADD_USER',
    LOADING_USER: 'LOADING_USER',
    REMOVE_USER: 'REMOVE_USER',
    ADD_CHATROOM: 'ADD_CHATROOM',
    ADD_MESSAGE: 'ADD_MESSAGE',
    LOADING_CHATROOMS: 'LOADING_CHATROOMS',
    REMOVE_CHATROOM: 'REMOVE_CHATROOM',
    UPDATE_CHATROOM: 'UPDATE_CHATROOM',
    SET_CHATROOMS: 'SET_CHATROOMS',
    SELECT_CHATROOM: 'SELECT_CHATROOM',
    REMOVE_SELECTED_CHATROOM: 'REMOVE_SELECTED_CHATROOM',
    SET_USER_CHATROOMS: 'SET_USER_CHATROOMS',
    ADD_USER_CHATROOM: 'ADD_USER_CHATROOM',
    REMOVE_USER_CHATROOM: 'REMOVE_USER_CHATROOM',
    UPDATE_USER_CHATROOM: 'UPDATE_USER_CHATROOM',


}

